development:
  adapter: postgresql
  database: be_se_dev
  username: rogera
  password: 1boris
  host: localhost

test:
  adapter: postgresql
  database: be_se_test
  username: rogera
  password: 1boris
  host: localhost


production:
  adapter: postgresql
  database: be_se_live
  username: rogera
  password: 1boris
  host: localhost

